### Definição de Variáveis Globais
@baseUrl = http://localhost:3002
@token = {{AuthLogin.response.body.token}}

###

# @name AuthLogin
POST {{baseUrl}}/auth/login
content-type: application/json

{
  "email": "josesilva12@gmail.com",
  "password": "qwe123qwewww"
}

###

# @name AuthRegisterUser
POST {{baseUrl}}/auth/register
content-type: application/json

{
  "name": "José da Silva3",
  "email": "josesilva12@gmail.com",
  "password": "qwe123qwewww",
  "photoUrl": "https://lasdijasidas.com",
  "role": 1
}

###

# @name AuthGetUserProfile
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}

###

# @name SoccerFieldGetAll
GET {{baseUrl}}/soccer-field
Authorization: Bearer {{token}}

###

# @name SoccerFieldGetAllByUser
GET {{baseUrl}}/soccer-field/by-user
Authorization: Bearer {{token}}

###

# @name SoccerFieldRegister
POST {{baseUrl}}/soccer-field
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "campo do zé",
  "pixKey": "Campo do zézinho2",
  "rentalValue": 150,
  "workStartTime": "10:00:00",
  "workFinishTime": "21:00:00",
  "workDays": ["segunda", "sexta"]
}

###

# @name SoccerFieldGetAvailableTimes
GET {{baseUrl}}/soccer-field/66fac90c0b7f0d8c63b94c8c?month=10
Authorization: Bearer {{token}}

###

# @name PlayerRegister
POST {{baseUrl}}/player
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "joao3",
  "stars": 4
}

###

# @name PlayerDelete
DELETE {{baseUrl}}/player/671bd6cde4c8bf61aee9549e
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name MatchRegister
POST {{baseUrl}}/match
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Partida de teste",
  "description":"Partida de teste.",
  "thumb": "Partida de teste",
  "soccerField": "66fac90c0b7f0d8c63b94c8c",
  "schedule": {
    "day": "20/08/2024",
    "startTime": "10:40:00",
    "finishTime": "14:40:00"
  }
}

###

# @name MatchUpdate
PUT {{baseUrl}}/match/66971ecd00f5b5b3f453ea94
content-type: application/json
Authorization: Bearer {{token}}

{
  "soccerField": "66ea1c97b6c878b4c7530ae3",
  "players": ["66ea1ca8b6c878b4c7530ae9", "66ea1cb2b6c878b4c7530aea"]
}

###

# @name MatchFindById
GET {{baseUrl}}/match/6699b0abdd6721079e440bd6
Authorization: Bearer {{token}}

###

# @name MatchGetAll
GET {{baseUrl}}/match
Authorization: Bearer {{token}}

###

# @name MatchCalculatePaymentPerPlayer
GET {{baseUrl}}/match/66ea191e8665af450bf9f33b/amount-paid-players
Authorization: Bearer {{token}}