### Testando registro de jogadores
POST http://localhost:3000/players
Content-Type: application/json

{
  "name": "John Doe",
  "team": "Team A"
}

### Testando quantidade de jogadores pagos em um match
GET http://localhost:3000/match/amount-paid-players/1
