# @name FetchAllSoccerFields
GET https://rachas-api.fyxuj9.easypanel.host/soccer-field
Content-Type: application/json

{
    "name": "mariquinha",
    "stars": 10
}

###

# @name RegisterSoccerField

POST http://localhost:8000/soccer-field
content-type: application/json

{
    "pixKey": "Campo do zézinho2",
    "rentalValue": 150,
    "workStartTime": "10:00:00",
    "workFinishTime": "21:00:00",
    "workDays": ["segunda", "sexta"]
}

###

# @name GetSoccerFieldAvailableTimes
GET http://localhost:3000/soccer-field/


# @name RegisterPlayer
POST http://localhost:3000/player
Content-Type: application/json

{
    "name": "mariquinha",
    "stars": 10
}

###

# @name RegisterMatch

POST http://localhost:3000/match
content-type: application/json

{
    "name": "Partida dos chuteiras de madeira",
    "description":"Ex id labore exercitation cillum. Cillum incididunt quis minim mollit ex dolor culpa velit ex reprehenderit id id sunt. Lorem labore eu elit ad quis voluptate.",
    "thumb": "somephoto.png",
    "soccerField": "66970c688810315138b0ad4f",
    "schedule": {
        "day": "20/08/2024",
        "startTime": "10:40:00",
        "finishTime": "14:40:00"
    }
}

###

# @name UpdateMatch

PUT http://localhost:3000/match/66971ecd00f5b5b3f453ea94
content-type: application/json

{
    "soccerField": "6692bc7e61b5fd78769bd2ca",
    "players": ["669719a0e73015f7572ad7ff", "669719c7e73015f7572ad801"]
}


###

# @name FindMatch
GET http://localhost:3000/match/6699b0abdd6721079e440bd6

###

# @name FetchAllMatch
GET http://localhost:3000/match

### 

# @name CalculatePaymentPerPlayer

GET http://localhost:3000/match/66970d12d8383a5a34caaae6/amount-paid-players